### ISSUE TITLE
Support folders in tar file

### ISSUE THREAD

**Issue by xtream1101** [xtream1101/s3-tar#1]
Currently all files, no mater the folder layout will be added in the root of the tar.

Should be able to preserve the path relative to the path added to be tar'd

**Comment by smuhit** [comment]
@xtream1101: Whenever you support this feature, it would be helpful to support both relative and absolute paths.

Meaning, if you're tarring everything in `my/folder` in your bucket, and there's a file called `my/folder/with/subdirectories/file.txt`, you should be able to support having the folder structure in the tar archive be `with/subdirectories/file.txt` or `my/folder/with/subdirectories/file.txt` (based on passed in parameters)

**Comment by xtream1101** [comment]
Added in [v0.1.6](https://github.com/xtream1101/s3-tar/tree/0.1.6)
