### ISSUE TITLE
Implausibly old timestamp error when extracting the tar.gz

### ISSUE THREAD

**Issue by py-prash** [xtream1101/s3-tar#5]
The files on S3 get successfully archived and compressed. And we are able to extract the files as well, but there is a warning that keeps popping up "Implausibly old timestamp 1969-12-31 00:00:00". And the file timestamps in the archive seems to be 1969-12-31. I believe its because the file stream gets created inside the tar.
Is there a solution for this?

**Comment by xtream1101** [comment]
That is because the timestamps were not getting saved into the tar file. That has been fixed in version `0.1.12`
