### ISSUE TITLE
Documentation for CLI usage

### ISSUE THREAD

**Issue by the1byo** [xtream1101/s3-tar#6]
Examples demonstrating the CLI usage would be very helpful.

**Comment by xtream1101** [comment]
Let me know if this helps, if not please let me know if there is a specific example you are looking for or if I need to explain anything better.
https://github.com/xtream1101/s3-tar#command-line

**Comment by the1byo** [comment]
Something like this was exactly what I was looking for. Thanks! Appreciate your prompt and diligent response.
